services:
  # Backend API Service
  - type: web
    name: medguide-backend
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_COOKIE_EXPIRE
        value: 30
      - key: CLIENT_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  # Frontend Static Site
  - type: web
    name: medguide-frontend
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_GEMINI_API_KEY
        sync: false
      - key: VITE_GEMINI_MODEL
        value: gemini-1.5-flash
